import './globals.css'
import { cn } from '~/lib/utils'
import type { Metadata } from 'next'
import { JetBrains_Mono } from 'next/font/google'
import Provider from '~/components/miscellaneous/provider'
import GotoTop from '~/components/miscellaneous/go-to-top'

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn('antialiased', jetbrainsMono.variable)}>
        <Provider>
          {children}
          <GotoTop />
        </Provider>
      </body>
    </html>
  )
}
